VAGRANTFILE_API_VERSION = "2"
BOX_NAME =  ENV['BOX_NAME'] || "centos"
BOX_URI = ENV['BOX_URI'] || "http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :host1 do |host1_config|
    host1_config.vm.box = BOX_NAME
    host1_config.vm.box_url = BOX_URI
    host1_config.vm.network :private_network, ip: "192.168.123.100"
    host1_config.vm.hostname = "host1.local"
    host1_config.vm.provision "ansible" do |ansible|
      ansible.limit = 'deploy'
      ansible.playbook = "deploy.yml"
      ansible.inventory_path = "inventory/vagrant"
      # ansible.verbose = "vvvv"
      ansible.sudo = true
    end
  end
end
